name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    - name: sbt to Maven Central
      uses: cosmincatalin/sbt-to-maven-central@v1.0.6
      env: 
        NEXUS_USER: ${{secrets.NEXUS_USER}}
        NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        GPG_PK: ${{secrets.GPG_PK}}
